### ISSUE TITLE
bug(pkg): missing src types folder since v0.5.3

### ISSUE THREAD

**Issue by douglasduteil** [jcs224/hono_sessions#16]
Before 
![image](https://github.com/jcs224/hono_sessions/assets/730511/3bb1c1a9-4c83-4599-a608-c01a61b09071)

After
![image](https://github.com/jcs224/hono_sessions/assets/730511/361dd131-21ed-493d-85e5-054dbd48ac80)

**Comment by jcs224** [comment]
:grimacing: Thanks for reporting this. I switched to using github actions for publishing the npm package when this started breaking. 0.5.6 should have them again.

I'll leave this open until I figure out what is going wrong with the github actions NPM.

**Comment by jcs224** [comment]
Should be working again as of 0.5.8. Fixed the github action. For some reason, my local `npm publish` behavior is different than Github Actions, and I had to be more strict in the `.npmignore` file to only exclude the root `src` directory and not the `src` folder in subdirectories.

**Comment by jcs224** [comment]
I also deprecated the non-working packages on NPM and removed the releases from Github.
