### ISSUE TITLE
getter and setter

### ISSUE THREAD

**Issue by tcurdt** [jcs224/hono_sessions#17]
It seems like `session.counter` could allow for better typing compared to `session.get('counter')`.
Any thoughts on maybe allowing for that?

I would like to have type safe session.
Also means I somehow need to extend the `Session` interface.

**Comment by jcs224** [comment]
This is a great idea!

I don't know how to do this currently, need to level up my Typescript skills :sweat_smile: but always accepting of PRs if someone is willing to tackle this before I get around to trying it.

**Comment by jcs224** [comment]
While I couldn't figure out a good way to make the session variables getters and setters such as `session.counter`, I was able to add strong typing to the current API using generics!

```ts
// Add types to your session data (optional)
type SessionDataTypes = {
  'counter': number
}

// Set up your Hono instance, using your types
const app = new Hono<{
  Variables: {
    session: Session<SessionDataTypes>,
    session_key_rotation: boolean
  }
}>()
```
