### ISSUE TITLE
Cookie expiring before the expireAfterSeconds

### ISSUE THREAD

**Issue by fhorray** [jcs224/hono_sessions#19]
Hello,

I'm encountering an issue where the cookie/session set on the client side is expiring before the configured expiration time. I have set the cookie to expire in 1 day (expireAfterSeconds: 86400), but it seems to expire much sooner. I don't know what might be causing this problem.

I’ve noticed that the cookie on the client side is being updated with each request to the API. This continuous updating might be contributing to the issue where the cookie is expiring sooner than expected or is it a normal thing to happen?

Could someone assist me in resolving this issue?

Below is the relevant code from my index.ts file:

```js
import { Hono } from "hono";
import { Env } from "types/bindings";
import { cors } from "hono/cors";
import { csrf } from "hono/csrf";
import { JwtVariables } from "hono/jwt";
import { Session, sessionMiddleware, CookieStore } from "hono-sessions";

const app = new Hono<{
  Bindings: Env;
  Variables: JwtVariables & {
    session: Session;
  };
}>().basePath("/v1");

app.use("*", async (c, next) => {
  const csrfMiddleware = csrf({
    origin: [
      "https://mydomain.com",
      "https://www.mydomain.com",
      "https://app.mydomain.com",
    ],
  });

  return csrfMiddleware(c, next);
});

app.use("*", async (c, next) => {
  const corsMiddleware = cors({
    origin: c.env.FRONTEND_URL, // Allowing only localhost:3000
    allowMethods: ["GET", "POST", "PATCH", "OPTIONS", "DELETE"],
    allowHeaders: ["Authorization", "Content-Type"],
    credentials: true,
  });

  return corsMiddleware(c, next);
});

const store = new CookieStore();
app.use("*", async (c, next) => {
  const sessionMid = sessionMiddleware({
    store,
    encryptionKey: c.env.SESSION_SECRET,
    expireAfterSeconds: 86400, // 1 day
    cookieOptions: {
      sameSite: "none",
      path: "/", 
      httpOnly: true, 
      secure: true, 
      domain: ".psycohub.com",
    },
    sessionCookieName: "session",
  });

  return sessionMid(c, next);
});

export default app;
```

**Comment by jcs224** [comment]
Setting a cookie `Expires` well into the future, beyond the `expireAfterSeconds`, might fix this. Apparently, if `Expires` isn't set on the cookie, it will close when you close the browser.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#expiresdate

You could also try setting `Max-Age`
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#max-agenumber

For example:

```
// ...
cookieOptions: {
  sameSite: "none",
  path: "/", 
  httpOnly: true, 
  secure: true, 
  domain: ".psycohub.com",
  maxAge: 86400 // the same or higher than 'expireInSeconds'
},
```
