### ISSUE TITLE
Update hono dependency to 3.11.7 or later to fix security issue

### ISSUE THREAD

**Issue by JoelEBorjesson** [jcs224/hono_sessions#5]
As title says, this update fixes an security issue with hono and their TrieRouter

Have a nice day:)

**Comment by jcs224** [comment]
Hi there,

The security issue in Hono shouldn't have any impact on the security of this package. If you wish to use the latest version of Hono with this package, you can use the `overrides` feature of NPM `package.json` to overcome the type mismatch between versions. The only use of Hono as a dependency in this package is for the types.

https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides
